<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="BubbleSort_tests.TestBubbleSort-20171102113916" skipped="0" tests="3" time="0.018">
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_bubble_sort" time="0.000"/>
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_get_number_tosort" time="0.001"/>
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_get_number_tosort_exception" time="0.017">
		<error message="issubclass() arg 2 must be a class or tuple of classes" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/asha/eclipse-workspace/MyApp/myappdev/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/asha/eclipse-workspace/MyApp/src/unittest/python/BubbleSort_tests.py", line 22, in test_get_number_tosort_exception
    self.assertRaises(False, True)
  File "/usr/lib/python2.7/unittest/case.py", line 473, in assertRaises
    callableObj(*args, **kwargs)
  File "/usr/lib/python2.7/unittest/case.py", line 117, in __exit__
    if not issubclass(exc_type, self.expected):
TypeError: issubclass() arg 2 must be a class or tuple of classes
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[[6, 7, 5, 4, 3, 2, 1]
[5, 7, 6, 4, 3, 2, 1]
[5, 6, 7, 4, 3, 2, 1]
[4, 6, 7, 5, 3, 2, 1]
[4, 5, 7, 6, 3, 2, 1]
[4, 5, 6, 7, 3, 2, 1]
[3, 5, 6, 7, 4, 2, 1]
[3, 4, 6, 7, 5, 2, 1]
[3, 4, 5, 7, 6, 2, 1]
[3, 4, 5, 6, 7, 2, 1]
[2, 4, 5, 6, 7, 3, 1]
[2, 3, 5, 6, 7, 4, 1]
[2, 3, 4, 6, 7, 5, 1]
[2, 3, 4, 5, 7, 6, 1]
[2, 3, 4, 5, 6, 7, 1]
[1, 3, 4, 5, 6, 7, 2]
[1, 2, 4, 5, 6, 7, 3]
[1, 2, 3, 5, 6, 7, 4]
[1, 2, 3, 4, 6, 7, 5]
[1, 2, 3, 4, 5, 7, 6]
[1, 2, 3, 4, 5, 6, 7]
Fully Sorted :[1, 2, 3, 4, 5, 6, 7]
]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
