<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="BubbleSort_tests.TestBubbleSort-20171101190853" skipped="0" tests="1" time="0.001">
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_sample_test" time="0.001">
		<error message="test_sample_test() takes exactly 3 arguments (2 given)" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "/home/asha/eclipse-workspace/MyApp/myappdev/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
TypeError: test_sample_test() takes exactly 3 arguments (2 given)
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
