<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" name="BubbleSort_tests.TestBubbleSort-20171101191259" skipped="0" tests="1" time="0.001">
	<testcase classname="BubbleSort_tests.TestBubbleSort" name="test_sample_test" time="0.001">
		<error message="&lt;module 'BubbleSort' from '/home/asha/eclipse-workspace/MyApp/src/main/python/BubbleSort.pyc'&gt; does not have the attribute 'get_number_tosort'" type="AttributeError">
<![CDATA[Traceback (most recent call last):
  File "/home/asha/eclipse-workspace/MyApp/myappdev/local/lib/python2.7/site-packages/mock/mock.py", line 1297, in patched
    arg = patching.__enter__()
  File "/home/asha/eclipse-workspace/MyApp/myappdev/local/lib/python2.7/site-packages/mock/mock.py", line 1369, in __enter__
    original, local = self.get_original()
  File "/home/asha/eclipse-workspace/MyApp/myappdev/local/lib/python2.7/site-packages/mock/mock.py", line 1343, in get_original
    "%s does not have the attribute %r" % (target, name)
AttributeError: <module 'BubbleSort' from '/home/asha/eclipse-workspace/MyApp/src/main/python/BubbleSort.pyc'> does not have the attribute 'get_number_tosort'
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
